### ISSUE TITLE
Deploy the website to a '.com.br' domain**

### ISSUE THREAD

**Issue by Nmartins6** [Nmartins6/clone-tabnews#2]
**Description:**  
Set up and configure the website to be accessible via a '.com.br' domain.

**Tasks:**  
- [x] acquire a suitable '.com.br' domain.  
- [x] Configure DNS settings to point to the hosting server.  
- [x] Deploy the application to the selected hosting service.  
- [x] Test the domain to ensure the website is accessible and fully functional.
