### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by Nmartins6** [Nmartins6/clone-tabnews#6]
## Task: Set Up and Implement Tests

- [x] Install the **Test Runner**.
- [x] Create a **test example** to validate the setup.
- [x] Write a **real test** for application functionality.
