### ISSUE TITLE
Local database

### ISSUE THREAD

**Issue by Nmartins6** [Nmartins6/clone-tabnews#7]
***Tasks***

- [x] Create endpoint `/status`.
- [x] Set up a local database.
- [x] move `.env` to `.env.development`.
- [x] add sercives scripts.
- [x] add `jsconfig.json` with `baseUrl`.
- [ ] Create a `database.js` module.
